"""add chatting room create user

Revision ID: 2d87b49030b2
Revises: 3668a38e231d
Create Date: 2021-04-20 16:55:31.878794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d87b49030b2'
down_revision = '3668a38e231d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatting_rooms', sa.Column('create_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chatting_rooms', 'users', ['create_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chatting_rooms', type_='foreignkey')
    op.drop_column('chatting_rooms', 'create_user_id')
    # ### end Alembic commands ###
