"""revise message relation with user

Revision ID: f7a1a9d23263
Revises: 8cdd663125b3
Create Date: 2021-04-16 15:36:13.821223

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from app import models


# revision identifiers, used by Alembic.
revision = 'f7a1a9d23263'
down_revision = '8cdd663125b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('receiver_id', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('sender_id', sa.Integer(), nullable=True))
    op.drop_constraint('messages_user_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'messages', 'users', ['receiver_id'], ['id'], ondelete='SET NULL')
    op.drop_column('messages', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_user_id_fkey', 'messages', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('messages', 'sender_id')
    op.drop_column('messages', 'receiver_id')
    # ### end Alembic commands ###
