"""first migration

Revision ID: ffd7186e9b90
Revises: 
Create Date: 2021-04-16 10:57:40.726535

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from app import models

# revision identifiers, used by Alembic.
revision = '8cdd663125b3'
down_revision = None
branch_labels = None
depends_on = None
import uuid
def gen_username():
    return uuid.uuid4().hex



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatting_rooms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login_id', sa.String(length=50), nullable=False),
    sa.Column('username', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('create_dt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_dt', sa.DateTime(timezone=True), server_default=sa.text('now()'), onupdate=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True, default=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('create_dt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('read_dt', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['chatting_rooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_room_r',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['chatting_rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'room_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_room_r')
    op.drop_table('messages')
    op.drop_table('users')
    op.drop_table('chatting_rooms')
    # ### end Alembic commands ###
